### PR TITLE
Snyder

### PR DESCRIPTION
**Pull request by betelgeuse234**

### CODE REVIEW

**Review by jfri2 — APPROVED** [review]
I like it.

**Comment by jfri2** [comment]
.atsuo are Atmel Studio autosave files - from what I remember everytime I open a project up it creates a new autosave file without regard to the fact that no changes have been made

**Comment by jfri2** [comment]
Crap. This might need some updating - can you update your local repo from dev and open a new PR? There might be a conflict with the fact mine was just pushed and then this one opened

**Comment by jfri2** [comment]
Wont let me merge this. Closing for now. Will add to .gitignore all .atsuo files as they are screwy

**Comment by betelgeuse234** [comment]
Yeah that's what I was going to do.

**Comment by jfri2** [comment]
Can you approve my PR to dev then update your branch from dev? That should
get rid of the issues.

**Pull request closed without merging**
